2013-03-30 11:44:41+0800 [-] Log opened.
2013-03-30 11:44:41+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "setup.py", line 194, in <module>
	    main()
	  File "setup.py", line 183, in main
	    SqlOprate.sqlUnpnConnect(key,dic)
	--- <exception caught here> ---
	  File "/Users/chengdh/myproject/GPSServer/TCPServer/SqlOpration/SqlOprate.py", line 26, in sqlUnpnConnect
	    conn = MySQLdb.connect(host=dic['mysqlHost'], user=dic['mysqlUser'],passwd=dic['mysqlPasswd'] ,db=dic['db'],charset='utf8')
	  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
	    return Connection(*args, **kwargs)
	  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
	    super(Connection, self).__init__(*args, **kwargs2)
	_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
	
2013-03-30 11:44:41+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "setup.py", line 194, in <module>
	    main()
	  File "setup.py", line 184, in main
	    SqlOprate.sqlUnpnhisConnect(key,dic)
	--- <exception caught here> ---
	  File "/Users/chengdh/myproject/GPSServer/TCPServer/SqlOpration/SqlOprate.py", line 35, in sqlUnpnhisConnect
	    c=MySQLdb.connect(host=dic['mysqlHost'], user=dic['mysqlUser'],passwd=dic['mysqlPasswd'] ,db=dic['unpn_history'],charset='utf8')
	  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
	    return Connection(*args, **kwargs)
	  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
	    super(Connection, self).__init__(*args, **kwargs2)
	_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
	
2013-03-30 11:44:41+0800 [-] YaxunFactory starting on 9008
2013-03-30 11:44:41+0800 [-] Starting factory <Factory.YaxunServerFactory.YaxunFactory instance at 0x109049440>
2013-03-30 11:45:11+0800 [-] start
2013-03-30 11:45:11+0800 [-] {'Yaxun': {'enable': True, 'serverPort': 9008, 'mysqlHost': 'localhost', 'mysqlUser': 'root', 'db': 'myPythonServerTestdb', 'factory': <Factory.YaxunServerFactory.YaxunFactory instance at 0x1093f8878>, 'unpn_history': 'unpnhis', 'mysqlPasswd': 'antongroot'}}
2013-03-30 13:12:17+0800 [-] Received SIGINT, shutting down.
2013-03-30 13:12:17+0800 [Factory.YaxunServerFactory.YaxunFactory] (TCP Port 9008 Closed)
2013-03-30 13:12:17+0800 [Factory.YaxunServerFactory.YaxunFactory] Stopping factory <Factory.YaxunServerFactory.YaxunFactory instance at 0x109049440>
2013-03-30 13:12:17+0800 [-] Main loop terminated.
